[package]
name = "frida"
version = "0.4.1"
authors = ["Keegan Saunders <keegan@undefinedbehaviour.org>"]
edition = "2018"
license = "wxWindows"
repository = "https://github.com/frida/frida-rust"
description = "Rust bindings for Frida"

[features]
auto-download = ["frida-sys/auto-download"]

[dependencies]
frida-sys = { path = "../frida-sys", version = "0.4.1" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.100"
thiserror = "1.0.43"

[dev-dependencies]
lazy_static = "1"

[badges]
maintenance = { status = "experimental" }

[package.metadata.docs.rs]
features = []
rustdoc-args = ["--cfg", "doc_cfg"]
